name: Sanity Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run testAddToCart

 #     - name: Slack Notification
 #       uses: rtCamp/action-slack-notify@v2
 #       env:
 #           SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
 #           SLACK_ICON: https://github.com/rtCamp.png?size=48
 #           SLACK_MESSAGE: 'Test Automation Report: https://github.com/Vaibh-Sontakke/Cypress-Automation/actions/runs/${{github.run_id}}'
 #           SLACK_TITLE: Cypress Web Test
 #           SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}