name: Parellel Tests

on: push

jobs:
 AddToCart-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run testAddToCart
        
      - uses: actions/upload-artifact@v4
        with:
            name: Mochawesome HTML Reoprt
            path: cypress/reports/html

 Registration-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run testRegistration

      - uses: actions/upload-artifact@v4
        with:
            name: Mochawesome HTML Reoprt
            path: cypress/reports/html

 SampleTest-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run testSample

      - uses: actions/upload-artifact@v4
        with:
            name: Mochawesome HTML Reoprt
            path: cypress/reports/html